
/*
 * This file is autogenerated by gen.js and any changes to it will be overwritten.
 **/

import icons_path from "./icons.svg";
export const path = icons_path;

export const enum Icons {
    Home = "home",
    Sun = "sun",
    Moon = "moon",
    Translate = "translate",
    MobilePhone = "mobile-phone",
    Menu = "menu",
    Users = "users",
    SmileyHalf = "smiley-half",
    Balloon = "balloon",
    ChevronDown = "chevron-down",
    Send = "send",
    Plus = "plus",
    Save = "save",
    Pencil = "pencil",
    PushPin = "push-pin",
    ArrowThinRight = "arrow-thin-right",
    Paste = "paste",
    Trash = "trash",
    TrashOpen = "trash-open",
    Clipboard = "clipboard",
    Copy = "copy",
    ChatMessage = "chat-message",
    TriangleAlert = "triangle-alert",
    Lock = "lock",
    Crown = "crown",
    Cogwheel = "cogwheel",
    Speaker = "speaker",
    SpeakerDeaf = "speaker-deaf",
    Microphone = "microphone",
    MicrophoneMute = "microphone-mute",
    Close = "close",
    FullscreenOff = "fullscreen-off",
    FullscreenOn = "fullscreen-on",
    Logout = "logout",
    CircleEmptyInfo = "circle-empty-info",
    PlainTextFile = "plain-text-file",
    RichTextFile = "rich-text-file",
    AudioFile = "audio-file",
    VideoFile = "video-file",
    ImageFile = "image-file",
    SpreadsheetFile = "spreadsheet-file",
    DatabaseFile = "database-file",
    ProgramFile = "program-file",
    TerminalFile = "terminal-file",
    ScriptFile = "script-file",
    PresentationFile = "presentation-file",
    UnknownFile = "unknown-file",
    CodeFile = "code-file",
    EncryptedFile = "encrypted-file",
    KeyFile = "key-file",
    ZipFile = "zip-file",
}

export { default as HomeIcon } from "./icons/google-material-icons/round/home.svg";
export { default as SunIcon } from "./icons/google-material-icons/outlined/light_mode.svg";
export { default as MoonIcon } from "./icons/google-material-icons/outlined/dark_mode.svg";
export { default as TranslateIcon } from "./icons/google-material-icons/sharp/translate.svg";
export { default as MobilePhoneIcon } from "./icons/google-material-icons/round/phone_iphone.svg";
export { default as MenuIcon } from "./icons/google-material-icons/sharp/menu.svg";
export { default as UsersIcon } from "./icons/google-material-icons/sharp/groups.svg";
export { default as SmileyHalfIcon } from "./icons/google-material-icons/round/sentiment_satisfied.svg";
export { default as BalloonIcon } from "./icons/modified/phosphor/balloon-fill.svg";
export { default as ChevronDownIcon } from "./icons/google-material-icons/round/keyboard_arrow_down.svg";
export { default as SendIcon } from "./icons/modified/phosphor/paper-plane-tilt-fill.svg";
export { default as PlusIcon } from "./icons/modified/phosphor/plus-bold.svg";
export { default as SaveIcon } from "./icons/google-material-icons/sharp/file_download.svg";
export { default as PencilIcon } from "./icons/google-material-icons/filled/edit.svg";
export { default as PushPinIcon } from "./icons/modified/phosphor/push-pin-bold.svg";
export { default as ArrowThinRightIcon } from "./icons/modified/phosphor/arrow-thin-right.svg";
export { default as PasteIcon } from "./icons/google-material-icons/round/content_paste_go.svg";
export { default as TrashIcon } from "./icons/google-material-icons/filled/delete.svg";
export { default as TrashOpenIcon } from "./icons/modified/google-material-icons/delete-filled--open.svg";
export { default as ClipboardIcon } from "./icons/google-material-icons/round/content_paste.svg";
export { default as CopyIcon } from "./icons/google-material-icons/round/content_copy.svg";
export { default as ChatMessageIcon } from "./icons/google-material-icons/filled/chat_bubble_outline.svg";
export { default as TriangleAlertIcon } from "./icons/google-material-icons/outlined/report_problem.svg";
export { default as LockIcon } from "./icons/google-material-icons/filled/lock.svg";
export { default as CrownIcon } from "./icons/modified/phosphor/crown-fill.svg";
export { default as CogwheelIcon } from "./icons/google-material-icons/round/settings.svg";
export { default as SpeakerIcon } from "./icons/google-material-icons/round/volume_up.svg";
export { default as SpeakerDeafIcon } from "./icons/google-material-icons/round/volume_off.svg";
export { default as MicrophoneIcon } from "./icons/google-material-icons/round/mic.svg";
export { default as MicrophoneMuteIcon } from "./icons/google-material-icons/round/mic_off.svg";
export { default as CloseIcon } from "./icons/google-material-icons/round/close.svg";
export { default as FullscreenOffIcon } from "./icons/google-material-icons/filled/fullscreen_exit.svg";
export { default as FullscreenOnIcon } from "./icons/google-material-icons/filled/fullscreen.svg";
export { default as LogoutIcon } from "./icons/google-material-icons/filled/logout.svg";
export { default as CircleEmptyInfoIcon } from "./icons/google-material-icons/outlined/info.svg";
export { default as PlainTextFileIcon } from "./icons/font-awesome/file-lines-solid.svg";
export { default as RichTextFileIcon } from "./icons/font-awesome/file-lines-solid.svg";
export { default as AudioFileIcon } from "./icons/font-awesome/file-audio-solid.svg";
export { default as VideoFileIcon } from "./icons/font-awesome/file-video-solid.svg";
export { default as ImageFileIcon } from "./icons/font-awesome/file-image-solid.svg";
export { default as SpreadsheetFileIcon } from "./icons/font-awesome/file-excel-solid.svg";
export { default as DatabaseFileIcon } from "./icons/font-awesome/file-solid.svg";
export { default as ProgramFileIcon } from "./icons/font-awesome/file-solid.svg";
export { default as TerminalFileIcon } from "./icons/font-awesome/file-code-solid.svg";
export { default as ScriptFileIcon } from "./icons/font-awesome/file-code-solid.svg";
export { default as PresentationFileIcon } from "./icons/font-awesome/file-powerpoint-solid.svg";
export { default as UnknownFileIcon } from "./icons/font-awesome/file-circle-question-solid.svg";
export { default as CodeFileIcon } from "./icons/font-awesome/file-code-solid.svg";
export { default as EncryptedFileIcon } from "./icons/font-awesome/file-shield-solid.svg";
export { default as KeyFileIcon } from "./icons/font-awesome/file-shield-solid.svg";
export { default as ZipFileIcon } from "./icons/font-awesome/file-zipper-solid.svg";

